name: Run main.go on Merge

on:
  push:
    branches:
      - master

jobs:
  run-go-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
    
    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Build and Run main.go
      run: |
        readme_content=$(go run main.go)
      
    - name: Update README
      run: |
        # Update README.md
        echo "$readme_content"
        echo "$readme_content" > README.md

        git add README.md
        git commit -m "Update README via Github Actions"
        git push
